target-version = "py312"
line-length = 100
extend-exclude = ["temp", "liberty_script"]



lint.select = [
  "E",   # pycodestyle errors
  "W",   # pycodestyle warnings
  "F",   # pyflakes
  "I",   # isort
  'UP',  # pyupgrade
  'A',   # flake8-builtins
  "C4",  # flake8-comprehensions
  'EXE', # flake8-executable
  'FA',  # flake8-future-annotations
  'PT',  # flake8-pytest-style
  'RSE', # flake8-raise
  'SIM', # flake8-simplify
  'DTZ', # flake8-datetimez, https://beta.ruff.rs/docs/rules/#flake8-datetimez-dtz
]

lint.ignore = [
  'A003',
  'DTZ007', # Naive datetime constructed using `datetime.datetime.strptime()` without %z
  'E501',
  'E711',
  'E712',
  # 'E721', # type comparison
  'E722',   # Do not use bare except
  'E741',
  'F401',   # unused imports
  'F841',
  'SIM102',
  'SIM105',
  'SIM108',
  'SIM115',
]

[format]
quote-style = "single"

[lint.isort]
known-first-party = ["lib"]
lines-after-imports = 2

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true
